### ISSUE TITLE
valid inputs for image viewer

### ISSUE THREAD

**Issue by janCstoffregen** [nie-ine/inseri#378]
hi, please give me some valid input for 

                   [iiifImagePath]="app.fileValueAsUrl"
                        [maxImageWidth]="app.stillImageFileValueHasDimX"
                        [maxImageHeight]="app.stillImageFileValueHasDimY"

thank you!

**Comment by rfbaumgartner** [comment]
Inputs `height` and `width` containing the size of the popup were missing since commit https://github.com/nie-ine/inseri/commit/ae3ac9c03bde9d906ca89e593783ba7a6cd24f38. Thus the image viewer has size 0 which makes it invisible.
Now, trying to fix resizing.

The same seems to be valid for the variable `hoveredElement` that enables synchronizing highlighting between different views of the same content.

**Comment by janCstoffregen** [comment]
thank you!!

**Comment by rfbaumgartner** [comment]
Image viewer now appears as wanted and resizes with its app.
