### ISSUE TITLE
Multiple pie chart apps on the same page

### ISSUE THREAD

**Issue by cyrill-martin** [nie-ine/inseri#467]
I tried to add 3 pie charts to a page. There are now 3 pie chart windows on that page with according titles and correct data management settings but the actual pie charts are all shown in only one of the three windows. 

http://test-nieos.nie-ine.ch/page?actionID=5e5f5801fd54d5001ea466e3&page=5ed8c610ac94d1001e4793c7

**Comment by janCstoffregen** [comment]
it should work now, please reopen this if it's still a bug.
there were several aspects that caused this bug.
- due to refactoring, the variable "numberOfInitialisedComponent" in the d3.js apps did not arrive in the component instance
- due to query speedup, the appInputQueryMapping and page variable were loaded too late and the data-assignment.component was triggered by ngOnChanges too early, thus not all variables were defined for the routine "startPathUpdateProcess()" in data-assignment.component.

**Comment by janCstoffregen** [comment]
I'll update the testserver soon and will write sth on slack then
