### ISSUE TITLE
Open Data MGMT directly from app settings

### ISSUE THREAD

**Issue by janCstoffregen** [nie-ine/inseri#521]
@domsteinbach danke für den Input!

**Comment by domsteinbach** [comment]
Actually it is already where I like it to be: Menu "File options", where a user is able to change the input.
But I would like to rename that menu entry. Instead of App-menu --> "File options" I would propose "data input" or sth. similar. Here the data input of the app is defined, no matter where it is coming from - from a response of a query/request or from a given file. For a user it is the same use case, so it should be the same work flow too.

**Comment by janCstoffregen** [comment]
done
