### ISSUE TITLE
Create a template for Raeber

### ISSUE THREAD

**Issue by janCstoffregen** [nie-ine/inseri#549]
@hanscools 

users can add the raeber-template to their project where they can perform sparql-queries themselves, 

-- I think one template for sparql queries
-- and one template for machine reasoning with raeber data

**Comment by hanscools** [comment]
Maybe this is also what you meant, but just for clarity, the template is a set of preformed SPARQL-queries to query the Raeber RDF-graph, to get an idea of the semantics used in the project, and how general ontologies are re-used, rather than a template that can be reused 100% directly for another project. Similarly for the N3-rules and MR.

**Comment by janCstoffregen** [comment]
yes, sorry for the lack of precision, this is what I meant as well

**Comment by janCstoffregen** [comment]
@Padlina @hanscools I talked to hans and we will create one or more templates here, can I assign this to you two?
